In [1]:
import numpy as np
from scipy.linalg import solve

In [2]:
Es = 30.0e6
Ea = 10.0e6
P1 = 500.0
P2 = 200.0
h1 = 12.0
h2 = 8.0
h3 = 10.0
d1 = 4.0
d2 = 2.5
d3 = 2.0
A1 = 0.25*d1**2
A2 = 0.25*d2**2
A3 = 0.25*d3**2

In [3]:
a1 = Es*A1/h1
a2 = Ea*A2/h2
a3 = Es*A3/h3
print('%.3e' % a1)
print('%.3e' % a2)
print('%.3e' % a3)

1.000e+07
1.953e+06
3.000e+06


In [4]:
p2 = 200.0*1000.0
p1 = 500.0*1000.0

In [5]:
K = np.pi*np.array([
    [a1 + a2, -a2, 0],
    [-a2, a2 + a3, -a3],
    [0, -a3, a3]
])
K

array([[ 37551849.68744049,  -6135923.15154256,         0.        ],
       [ -6135923.15154256,  15560701.11231194,  -9424777.96076938],
       [        0.        ,  -9424777.96076938,   9424777.96076938]])

In [10]:
Q = np.array([[0], [-p2], [p1]])

In [11]:
Q

array([[      0.],
       [-200000.],
       [ 500000.]])

In [12]:
solve(K, Q)

array([[ 0.0095493 ],
       [ 0.0584417 ],
       [ 0.11149334]])

In [8]:
Q

array([      0., -200000.,  500000.])