# Question 3

In [1]:
import numpy as np
from numpy.linalg import qr, eig

In [2]:
np.set_printoptions(
    suppress=True, 
    formatter={
        'float': lambda x: '%.2f' % x,
        'complexfloat': lambda x: '%.2f + %.2fi' % (x.real, x.imag)
    }, 
    linewidth=100
)

In [3]:
def step_generator(A):
    for i in range(1000): # Dummy step
        Q, R = qr(A)
        A = R.dot(Q)
        yield A

## a)

In [4]:
A = np.array([[5, 4, 1, 1], [4, 5, 1, 1], [1, 1, 4, 2], [1, 1, 2, 4]])

In [5]:
Ak = step_generator(A)

In [6]:
next(Ak)

array([[9.60, 0.93, 1.10, -0.40],
       [0.93, 1.10, 0.12, -0.04],
       [1.10, 0.12, 4.90, -1.07],
       [-0.40, -0.04, -1.07, 2.39]])

In [7]:
next(Ak)

array([[9.92, 0.10, 0.61, 0.09],
       [0.10, 1.00, 0.01, 0.00],
       [0.61, 0.01, 5.01, 0.43],
       [0.09, 0.00, 0.43, 2.06]])

The off-diagonal entries are decreasing, whereas the diagonal entries are converging to the eigenvalues. One could also say that the norm of the diagonal is increasing.

In other words, the iteration converges to a diagonal matrix containing the eigenvalues. This makes sense because $A$ is real and symmetric. 

## b)

In [8]:
A = np.array([[6, 4, 4, 1], [4, 6, 1, 4], [4, 1, 6, 4], [1, 4, 4, 6]])
Ak = step_generator(A)

In [9]:
next(Ak)

array([[13.13, 2.70, 2.87, 0.23],
       [2.70, 5.64, 0.68, 1.26],
       [2.87, 0.68, 5.72, 1.34],
       [0.23, 1.26, 1.34, -0.49]])

In [10]:
next(Ak)

array([[14.76, 1.08, 1.09, 0.02],
       [1.08, 5.11, 0.11, 0.24],
       [1.09, 0.11, 5.11, 0.25],
       [0.02, 0.24, 0.25, -0.98]])

Similar to **a)**

## c)

In [11]:
A = np.array([[33, 16, 72], [-24, -10, -57], [-8, -4, -17]])
Ak = step_generator(A)

In [12]:
next(Ak)

array([[3.94, 17.53, -102.39],
       [-0.04, 1.96, 3.61],
       [0.02, 0.02, 0.10]])

In [13]:
next(Ak)

array([[3.24, 20.78, 101.83],
       [-0.01, 2.05, -2.64],
       [-0.00, 0.02, 0.71]])

In [14]:
next(Ak)

array([[3.07, 23.04, -101.35],
       [-0.00, 2.04, 2.43],
       [0.00, -0.02, 0.88]])

In [15]:
next(Ak)

array([[3.02, 24.37, 101.04],
       [-0.00, 2.03, -2.37],
       [-0.00, 0.01, 0.95]])

In [16]:
next(Ak)

array([[3.01, 25.12, -100.86],
       [-0.00, 2.02, 2.36],
       [0.00, -0.01, 0.98]])

In this case, the diagonal entries converge to the correct eigenvalues but the matrix is upper triangular. However, $A$ is non-defective. Why is convergence slow?

In [17]:
vals, vecs = eig(A)
vecs

array([[0.78, 0.76, 0.76],
       [-0.59, -0.61, -0.62],
       [-0.20, -0.20, -0.19]])

The eigenvectors are nearly the same! This is the only explanation for slow convergence.

## d)

In [18]:
A = np.array([[6, -3, 4, 1], [4, 2, 4, 0], [4, -2, 3, 1], [4, 2, 3, 1]])
Ak = step_generator(A)

In [19]:
print(3. + np.sqrt(5))
print(3. - np.sqrt(5))

5.2360679775
0.7639320225


In [20]:
for i in range(10):
    next(Ak)
next(Ak)

array([[5.72, -8.51, -2.20, -0.06],
       [0.03, 4.75, 3.97, -2.66],
       [0.00, -0.00, 0.84, -1.18],
       [-0.00, -0.00, 0.00, 0.69]])

In [21]:
for i in range(10):
    next(Ak)
next(Ak)

array([[5.48, -8.53, -2.08, 0.07],
       [0.01, 5.00, 3.94, 2.79],
       [0.00, -0.00, 0.80, 1.18],
       [0.00, 0.00, -0.00, 0.73]])

In [22]:
for i in range(10):
    next(Ak)
next(Ak)

array([[5.40, -8.54, -2.05, -0.07],
       [0.00, 5.08, 3.93, -2.83],
       [0.00, -0.00, 0.79, -1.18],
       [-0.00, -0.00, 0.00, 0.74]])

In [23]:
vals, vecs = eig(A)
vecs

array([[-0.26 + 0.00i, 0.26 + 0.00i, -0.33 + 0.00i, -0.33 + -0.00i],
       [-0.62 + 0.00i, 0.62 + 0.00i, 0.11 + 0.00i, 0.11 + -0.00i],
       [-0.24 + 0.00i, 0.24 + 0.00i, 0.30 + -0.00i, 0.30 + 0.00i],
       [-0.71 + 0.00i, 0.71 + 0.00i, 0.89 + 0.00i, 0.89 + -0.00i]])

Two of the eigenvalues are defective: they have algeabric multiplicity of 2. Each eigenvalue also has geometric multiplicity of 1. 

Thus, convergence is very slow and the matrix is triangular. 

## e)

In [24]:
A = np.array([[4, -5, 0, 3], [0, 4, -3, -5], [5, -3, 4, 0], [3, 0, 5, 4]])
Ak = step_generator(A)

In [25]:
for i in range(10):
    next(Ak)
next(Ak)

array([[12.00, -0.00, 0.00, -0.00],
       [-0.00, 1.00, -5.00, 0.00],
       [0.00, 5.00, 1.00, 0.00],
       [-0.00, -0.00, -0.00, 2.00]])

It is easy to see that we have a 2x2 block in the middle, which corresponds to the complex eigenvalue pair, and two 1x1 at either corner! None of the eigenvalues are defective, hence the diagonal form. 

## f)

In [54]:
A = np.array([
    [10, -19, 17, -12, 4, 1], 
    [ 9, -18, 17, -12, 4, 1],
    [ 8, -16, 15, -11, 4, 1],
    [ 6, -12, 12, -10, 4, 1],
    [ 4,  -8,  8,  -6, 1, 2],
    [ 2,  -4,  4,  -3, 1, 0]
])
Ak = step_generator(A)

In [55]:
for i in range(500):
    next(Ak)
next(Ak)

array([[1.06, -20.48, 14.65, -45.17, -20.69, 1.38],
       [-0.03, -0.02, 1.31, -1.72, -1.77, -0.08],
       [0.02, 0.01, -1.04, 0.44, 1.52, 0.57],
       [0.04, 0.03, -0.08, -0.01, 0.59, -0.01],
       [0.00, 0.00, -0.00, 0.00, -1.00, 1.34],
       [0.00, 0.00, -0.00, 0.00, -0.00, -1.00]])

In this case, -1 is a defective eigenvalue with multiplicity 1 and we have a complex pair. The iteration is clearly not converging for the complex pair. It was said in the notes that defective eigenvalues are very sensitive, which is clearly the case here. 

In [28]:
vals, vecs = eig(A)
# Eigenvectors for the -1 eigenvalue
vecs.T[np.isclose(vals, -1.0)].T

array([[0.47 + 0.00i, -0.47 + 0.00i, -0.47 + -0.00i],
       [0.47 + 0.00i, -0.47 + 0.00i, -0.47 + -0.00i],
       [0.47 + 0.00i, -0.47 + 0.00i, -0.47 + -0.00i],
       [0.47 + 0.00i, -0.47 + 0.00i, -0.47 + -0.00i],
       [0.31 + 0.00i, -0.31 + -0.00i, -0.31 + 0.00i],
       [0.16 + 0.00i, -0.16 + -0.00i, -0.16 + 0.00i]])

Moreover, the eigenvalue -1 has geometric multiplicity of 1.

We could keep going with the iteration and it would never converge to the right eigenvalues.